### ISSUE TITLE
Title and h1 empty when title in input file is not found

### ISSUE THREAD

**Issue by JerryHue** [DukeManh/OSD_SSG#3] opened 2021-09-16 17:07 UTC
I created a file with the following text:

```
This is a text file

Let's say this appears.
```

Notice that there is only an empty line between the two line, so the first line is not considered a title. Due to this, the HTML file ends up with a missing title and and header. Also, `false` seems to be introduced before the header, although I am not sure why. Here's the input:

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="hello.txt/index.css"> 
        <title></title>
    </head>
    <body>
false
        <h1 class="text-center"></h1>
        <p>This is a text file</p>
        <p>Let's say this appears.</p>
        <h6 class="text-center"> End </h6>
    </body>
</html>
```

**Comment by DukeManh** [comment] 2021-09-16 17:13
This is the expected behavior as the title has to be followed by 2 blank lines.
See also the first requirement of the optional feature [0.1](https://github.com/Seneca-CDOT/topics-in-open-source-2021/wiki/release-0.1)

I'd say no title is parsed is due to users' input file's formatting issue.

**Comment by DukeManh** [comment] 2021-09-16 18:05
@JerryHue

**Comment by JerryHue** [comment] 2021-09-16 18:19
I would say that the title from the input file may not be required, and shouldn't be considered an error.

My reasoning is that, for the issues to look out for in [lab 1](https://github.com/Seneca-CDOT/topics-in-open-source-2021/wiki/lab-1), the markup and formatting of the HTML output file should be valid. Using [this validator](https://html5.validator.nu/), I have the following errors:

```
    Error: Element title must not be empty.

    From line 8, column 8; to line 8, column 15

    > ↩<title></title>↩</hea

    Warning: Empty heading.

    From line 12, column 1; to line 12, column 24

    dy>↩false↩<h1 class="text-center"></h1>↩'
```

**Comment by JerryHue** [comment] 2021-09-16 18:23
My suggestion would be, in the case of a title not being found, to outright not have a `<title>` and `<h1>` elements at all, or to keep the `<title>` element with the text being the filename of the file and not have the `<h1>` elements.

**Comment by DukeManh** [comment] 2021-09-16 18:24
Right, in that case, I would not render title and h1 if the title is not found.

**Comment by DukeManh** [comment] 2021-09-16 18:29
Could you test it again with the new commit https://github.com/DukeManh/OSD_SSG/commit/a7f0e33aaa22347d417653211c1279ddcb20177a

**Comment by DukeManh** [comment] 2021-09-16 18:42
Fixed via https://github.com/DukeManh/OSD_SSG/commit/a7f0e33aaa22347d417653211c1279ddcb20177a

**Closed as completed** 2021-09-16 18:42 UTC
